version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul_lapka
    restart: unless-stopped
    ports:
      - 8500:8500
    networks:
      - lapka

  fabio:
    image: fabiolb/fabio:latest
    container_name: fabio_lapka
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul_lapka:8500
    ports:
      - 9998:9998
      - 9999:9999
    networks:
      - lapka

  mongo:
    image: mongo
    container_name: mongo_lapka
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - lapka

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_lapka
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    networks:
      - lapka

  reddis:
    image: redis
    container_name: redis_lapka
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - lapka

  seq:
    image: datalust/seq
    container_name: seq_lapka
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - lapka

  minio:
    image: minio/minio
    container_name: minio_lapka
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio:/data
    networks:
      - lapka
    command: server --console-address ":9001" /data
    
  lapka:
    image: mobicommunity/lapkapets:1.0
    container_name: lapka_pets
    restart: unless-stopped
    ports:
     - 5002:5002
    networks:
     - lapka

networks:
  lapka:
    name: lapka

volumes:
  consul:
    driver: local
  mongo:
    driver: local
  redis-data:
    driver: local
  rabbitmq:
    driver: local
  seq:
    driver: local
  minio:
    driver: local
